name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Debug"

      - run: ${{ tojson(github.event) }}
        shell: cat {0}

      - run: echo ${{ github.event.pull_request.head.sha }}
      - run: echo ${{ github.event.after }}

  filter_jobs:
    name: Filter jobs
    runs-on: ubuntu-latest
    outputs:
      jsChanged: ${{ steps.filter.outputs.jsChanged }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.after }}
          # Should be kept in sync with the filter in the CI workflow
          filters: |
            jsChanged: 'src/index.js'

  setup:
    name: Setup
    runs-on: ubuntu-latest
    needs: filter_jobs
    if : ${{ needs.filter_jobs.outputs.jsChanged == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "Setup"
